### ISSUE TITLE
Medianizer for testnet/ganache

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra-v2#109]
From #108:

How do we map medianizer to Ganache (can prob deploy a fake contract). Reason for this is it would be nice to be able to run locally without requiring a network connection.

**Comment by bohendo** [comment]
Brain dump in preparation for implementing this:
 - The [medianizer address](https://github.com/ConnextProject/indra-v2/blob/master/modules/node/src/exchangeRate/exchangeRate.service.ts#L10) should be added to our project's address-book.json, that's already [being injected](https://github.com/ConnextProject/indra-v2/blob/master/ops/start-dev.sh#L28) into the node so we can slip this address in w all the others, no new env vars needed
 - Looks like `this.medianizer.compute()` is the only method we need, should be simple to create a dummy contract that implements this method & just returns a hard-coded value. We can add it to our existing [ganache migrations](https://github.com/ConnextProject/indra-v2/blob/master/ops/migrate-contracts.js)

**Comment by bohendo** [comment]
Update: This is not needed. There's no reason not to use the mainnet medianizer for all networks. Since we only ever use one contract on one network, hardcoding it's address seems fine for now.

**Comment by bohendo** [comment]
Note: there's a fallback hardcoded swapRate that'll be used if accessing the mainnet medianizer fails. This should still allow offline development, reopen this issue if that's not the case
