### ISSUE TITLE
Switch out assetId for coinId

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra-v2#141]
Should be consistent with the cf naming.

Done before launch to minimize refactoring for users later

**Comment by bohendo** [comment]
I kinda like assetId.. Seems like CF is refactoring often enough that we could sit tight w what we have until things settle down on their side.

**Comment by hthillman** [comment]
Can this be closed?

**Comment by rhlsthrm** [comment]
Probably, I'll defer to @LayneHaber on it.

**Comment by LayneHaber** [comment]
Yeah we can leave it as assetId, it has grown on me as well. I'll close it and we can reopen it if it's an issue later. We handle all the renaming in our client anyways, so should be abstracted from users
