### ISSUE TITLE
[node] Add collateralization in-flight check

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra-v2#181]
Currently, collateralization can be "spammed" if there is a request in flight. The current version only checks free balance, so until the free balance is updated by a deposit, it can be spammed.

**Comment by hthillman** [comment]
Can this be closed?

**Comment by rhlsthrm** [comment]
Nope, we still need to do this.

**Comment by LayneHaber** [comment]
[duplicate/related](https://github.com/ConnextProject/indra/issues/237)
