### ISSUE TITLE
App with provided hash has not been installed in link payments where sender == recipient

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra-v2#254]
```
this.appId:  0x89153ff4aac746d06414bde85489754c5feaed72b6b744dc864d805dae1f853a
appInfo:  { state:
   { finalized: true,
     linkedHash:
      '0x51848f7e3bc770250505938912fe8fceee9d37d39493edd8b0131b932345cc0b',
     stage: 1,
     transfers: [ [Array], [Array] ],
     turnNum: BigNumber { _hex: '0x01' } } }
```
That 0x518.. hash is the one I ask for later, then this gets logged:
```
[Nest] 169   - 08/09/2019, 10:35 AM   [NodeService] uninstallApp called with result {"appInstanceId":"0x89153ff4aac746d06414bde85489754c5feaed72b6b744dc864d805dae1f853a"}
```
So that linkedHash's appId gets uninstalled and then later we try to access it again and it fails
Updated error log so now it prints:
```
Error: App with provided hash has not been installed: 0x51848f7e3bc770250505938912fe8fceee9d37d39493edd8b0131b932345cc0b
    at TransferService.<anonymous> (/root/modules/node/src/transfer/transfer.service.ts:62:13)
    at Generator.next (<anonymous>)
    at fulfilled (/root/modules/node/src/transfer/transfer.service.ts:13:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Probably because the app gets uninstalled on the sender's side and then it can't find the app on the recipient's side since the sender is the recipient.

**Comment by rhlsthrm** [comment]
Do we want this case to work? We should handle this at the controller level and throw an error if `sender == recipient`.

**Comment by bohendo** [comment]
Yes this case should definitely work. Eg someone gives a link away and says "you have 7 days to redeem this" & they should be able to redeem their own link if the recipient never does

**Comment by hthillman** [comment]
@bohendo @rhlsthrm any update here?

**Comment by rhlsthrm** [comment]
We still need to do this.

**Comment by LayneHaber** [comment]
This worked for me on prod, closing this issue
