### ISSUE TITLE
'amount' misspelled in RedeemCard constructor

### ISSUE THREAD

**Issue by SeanJCasey** [ConnextProject/indra-v2#289]
https://github.com/ConnextProject/indra-v2/blob/5413f0f9c272bf703423017b38eca038d61f2e30/modules/daicard/src/components/redeemCard.js#L56

**Comment by hthillman** [comment]
Great catch @SeanJCasey. Will fix this.

**Comment by hthillman** [comment]
cc @bohendo -- I can just fix this typo unless you'd rather do it as part of a larger PR?

**Comment by rhlsthrm** [comment]
You should just put the fix in @hthillman, no point waiting on it.

**Comment by hthillman** [comment]
Fixed on staging, can merge to master whenever
